accessConfig:
  authenticationMode: API_AND_CONFIG_MAP
  accessEntries:
  - type: STANDARD
    accessPolicies:
    - policyARN: 'arn:aws:eks::aws:cluster-access-policy/AmazonEKSAdminPolicy'
      accessScope:
        type: cluster
    principalARN: 'arn:aws:iam::129008548655:role/trial-sync-argo-using-github-actions'
addonsConfig: {}
apiVersion: eksctl.io/v1alpha5
autoModeConfig:
  enabled: true
  nodePools:
  - general-purpose
  - system
  nodeRoleARN: 'arn:::::'
  permissionsBoundaryARN: 'arn:::::'
availabilityZones:
- ap-northeast-1a
- ap-northeast-1d
- ap-northeast-1c
cloudWatch:
  clusterLogging: {}
iam:
  vpcResourceControllerPolicy: true
  withOIDC: false
kind: ClusterConfig
kubernetesNetworkConfig:
  ipFamily: IPv4
metadata:
  name: trial-sync-argo-using-github-actions
  region: ap-northeast-1
  version: "1.34"
privateCluster:
  enabled: false
  skipEndpointCreation: false
upgradePolicy: {}
vpc:
  autoAllocateIPv6: false
  cidr: 192.168.0.0/16
  clusterEndpoints:
    privateAccess: false
    publicAccess: true
  manageSharedNodeSecurityGroupRules: true
  nat:
    gateway: Single
